chain:
  steps:
    - name: authHandler
      timeout: 2s
      retry: 1
    - name: validationHandler
      parallel: true
    - name: loggingHandler
      stopOnError: false
    - name: businessHandler
